source:
    test_dir: tests 

connection:
    database: db
    user:     uname
    password: pass
    hostname: localhost
    port:     50000

trusted_connection:
    auth_user: auth_user
    auth_pass: auth_pass
    tc_user:   tc_user
    tc_pass:   tc_pass
